### ISSUE TITLE
HTTP Server running on localhost:8000 ERROR

### ISSUE THREAD

**Issue by jowelhub** [gcrbr/malatia#1]
if i open on my browser the http://localhost:8000/ i get:

Error response
Error code: 404

Message: File not found.

Error code explanation: 404 - Nothing matches the given URI.

could you help me?

**Comment by gcrbr** [comment]
Should work now, thank you.

**Comment by jowelhub** [comment]
I did pull.
I dont know if am i doing it wrong, but sill i got the same problem.

I executed (since i already have data at data.json):
_> python main.py -io
MALATÌA <github.com/gcrbr>
HTTP Server running on localhost:8000_

And if I go to http://localhost:8000/
I still got:

_Error response
Error code: 404

Message: File not found.

Error code explanation: 404 - Nothing matches the given URI._

I suppose that I should see the interface like the example, right?

**Comment by gcrbr** [comment]
There must be something going on with the "interface" path. Could you please provide some information about the execution environment?

**Comment by jowelhub** [comment]
I'm using windows 11, Python 3.12.3, VS Code IDE.

Maybe is something about translate_path function, it's like i dont have acces to index.html, but i dont really know what is it.

I'm a CS student but I have never done web programming so I don't really know about js, html and these stuff

I asked chat gpt and in the older version it kinda worked if i did:

def translate_path(self, path: str) -> str:
    if path == '/':
        # Return the path to the index.html file in the interface directory
        return self.get_cwd() + '/index.html'
    elif path == '/data.json':
        return os.getcwd() + '/data.json'
    elif path in self.get_allowed_paths():
        return self.get_cwd() + path
    else:
        # Handle other paths if needed
        return ''

this showed the load and map buttons, but if i click on them didn't do anything, so it didn't work either.

**Comment by gcrbr** [comment]
Could you please try now?

**Comment by jowelhub** [comment]
![Captura de pantalla 2024-04-18 193708](https://github.com/gcrbr/malatia/assets/146464443/4ad2a85c-e117-4285-bc88-e306eef72c56)

**Comment by gcrbr** [comment]
Sorry for the wait, is it now working.

**Comment by jowelhub** [comment]
Nice! I just tested it and it works great, thanks! Out of curiosity, what was it?

**Comment by gcrbr** [comment]
I tested it on macOS only and forgot Windows used "\\" instead of "/" for paths, lol.
Enjoy your trips!

**Comment by jowelhub** [comment]
I’m very curious, since I’m trying to develop a similar project, and i want to ask some questions. If you don't want to, you don't have to respond.

I suppose you are a CS undergrad or grad. I suppose this is a side project and not an uni project. Have you learnt the frontend and api’s at university or by yourself? How did you get the api’s? Have you reverse engineered it by yourself? Or just got em from some github?

**Comment by gcrbr** [comment]
Feel free to send me an email at `gianspamcarlo at gmail dot com`.
